spring.application.name=api-gateway
server.port=8084

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=*
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.cloud.gateway.server.webflux.routes[0].id=POST-SERVICE
spring.cloud.gateway.server.webflux.routes[0].uri=lb://POST-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/posts/**

spring.cloud.gateway.server.webflux.routes[1].id=ems-backend
spring.cloud.gateway.server.webflux.routes[1].uri=lb://ems-backend
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/employees/**

spring.cloud.gateway.server.webflux.routes[2].id=notification-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://notification-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/v1/notifications/**

spring.cloud.gateway.server.webflux.routes[3].id=User-Service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/v1/users/**

logging.level.org.springframework.cloud.gateway=DEBUG
